server:
  port: 8012

spring:
  data:
    mongodb:
      host: 10.0.0.201
      port: 27018
#      username: sunny
#      password: 123456
      database: company

#      uri: mongodb://sunny:123456@127.0.0.1:27017/file