#spring:
#  datasource:
#      url: jdbc:mysql://10.0.0.12:3306/jupiter_india?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
#      username: jupiter
#      password: jda780319
#      driver-class-name: org.apache.hive.jdbc.HiveDriver
#      type: com.zaxxer.hikari.HikariDataSource
#      hikari:
#        minimum-idle: 5
#        maximum-pool-size: 50
#        auto-commit: true
#        idle-timeout: 30000
#        pool-name: DatebookHikariCP
#        max-lifetime: 1800000
#        connection-timeout: 60000
#        connection-test-query: SELECT 1
server:
  port: 8086
spring:
  hive:
      minimum-idle: 0
      maximum-pool-size: 2
      max-lifetime: 600000
      connection-timeout: 60000
      username: hive
      password:
      jdbc-url: jdbc:hive2://node2:10000/test_wind;transportMode=http;httpPath=cliservice
      driver-class-name: org.apache.hive.jdbc.HiveDriver
      testOnBorrow: false
#      type: com.zaxxer.hikari.HikariDataSource  TODO 等hive库好了测试一下
  hikari:
    minimum-idle: 5
    maximum-pool-size: 50
    auto-commit: true
    idle-timeout: 30000
    pool-name: DatebookHikariCP
    max-lifetime: 1800000
    connection-timeout: 60000
    connection-test-query: SELECT 1