hbase:
    config:
      hbase.zookeeper.quorum:  master.hadoop,salve1.hadoop  #data-test-001,data-test-002
      zookeeper.znode.parent: /hbase-unsecure
      hbase.client.retries.number: 10
      hbase.client.keyvalue.maxsize: 31457280

server:
      port: 9903

